
-- SEARCH INPATIENT BY DOCTOR ID
DELIMITER //
CREATE PROCEDURE search_inpatient_by_doc_id (IN DOCCODE CHAR(6))
BEGIN
	SELECT ID, NAME, GENDER, ADDRESS, PHONE
	FROM 
		(SELECT CONCAT(PREFIX, POSTFIX) AS ID, 
				CONCAT_WS(' ', FNAME, LNAME) AS NAME, 
				GENDER, ADDRESS, PHONE 
				FROM INPATIENT) AS TEMP
	WHERE ID IN
		(SELECT CONCAT(IPREFIX, IPOSTFIX) AS ID 
				FROM TREATMENT
				WHERE DCODE = DOCCODE);
END //

-- SEARCH OUTPATIENT BY DOCTOR ID
DELIMITER //
CREATE PROCEDURE search_outpatient_by_doc_id (IN DOCCODE CHAR(6))
BEGIN
	SELECT ID, NAME, GENDER, ADDRESS, PHONE
	FROM 
		(SELECT CONCAT(PREFIX, POSTFIX) AS ID, 
				CONCAT_WS(' ', FNAME, LNAME) AS NAME, 
				GENDER, ADDRESS, PHONE 
				FROM OUTPATIENT) AS TEMP
	WHERE ID IN
		(SELECT CONCAT(OPREFIX, OPOSTFIX) AS ID 
				FROM EXAMINATION
				WHERE DCODE = DOCCODE);
END //		

-- GET ALL TREATMENT OF AN INPATIENT
DELIMITER //
CREATE PROCEDURE get_treatment_w_fee (IN PRE CHAR(2), IN POST CHAR(7))
BEGIN
	SELECT START_TIME, END_TIME, ADMISSION_DATE, IPREFIX, IPOSTFIX, FEE
	FROM TREATMENT
	WHERE IPREFIX = PRE AND IPOSTFIX = POST;
END //

-- GET ALL MEDICATION USED BY AN INPATIENT
DELIMITER //
CREATE PROCEDURE get_med_within_treatment (IN PRE CHAR(2), IN POST CHAR(7))
BEGIN
	SELECT U.START_TIME, U.END_TIME, U.ADMISSION_DATE, U.IPREFIX, U.IPOSTFIX, U.USE_QUANTITY, M.NAME, M.PRICE
	FROM
		USES AS U JOIN MEDICATION AS M 
		ON U.MCODE = M.MCODE
	WHERE U.IPREFIX = PRE AND U.IPOSTFIX = POST;
END //

-- GET ALL TREATMENT OF AN OUTPATIENT
DELIMITER //
CREATE PROCEDURE get_exam_w_fee (IN PRE CHAR(2), IN POST CHAR(7))
BEGIN
	SELECT TIME, OPREFIX, OPOSTFIX, FEE
	FROM EXAMINATION
	WHERE OPREFIX = PRE AND OPOSTFIX = POST;
END //

-- GET ALL MEDICATION USED BY AN INPATIENT
DELIMITER //
CREATE PROCEDURE get_med_within_exam (IN PRE CHAR(2), IN POST CHAR(7))
BEGIN
	SELECT C.TIME, C.OPREFIX, C.OPOSTFIX, C.CONSUME_QUANTITY, M.NAME, M.PRICE
	FROM
		CONSUMES AS C JOIN MEDICATION AS M 
		ON C.MCODE = M.MCODE
	WHERE C.OPREFIX = PRE AND C.OPOSTFIX = POST;
END //
